CREATE TABLE IF NOT EXISTS countries (id number(10) , name varchar(500));

Insert into countries (id, name) values (227,'España');
Insert into countries (id, name) values (229,'Uruguay');
Insert into countries (id, name) values (226,'Argentina');
Insert into countries (id, name) values (228,'Estados Unidos');
Insert into countries (id, name) values (353,'Fiyi');
Insert into countries (id, name) values (354,'Islas Marshall');
Insert into countries (id, name) values (355,'Islas Salomon');
Insert into countries (id, name) values (356,'Kiribati');
Insert into countries (id, name) values (357,'Micronesia');
Insert into countries (id, name) values (358,'Nauru');
Insert into countries (id, name) values (359,'Nueva Zelanda');
Insert into countries (id, name) values (360,'Palaos');
Insert into countries (id, name) values (361,'Papua Nueva Guinea');
Insert into countries (id, name) values (362,'Samoa');
Insert into countries (id, name) values (363,'Tonga');
Insert into countries (id, name) values (364,'Tuvalu');
Insert into countries (id, name) values (365,'Vanuatu');
Insert into countries (id, name) values (366,'Angola');
Insert into countries (id, name) values (367,'Argelia');
Insert into countries (id, name) values (368,'Benin');
Insert into countries (id, name) values (369,'Botsuana');
Insert into countries (id, name) values (370,'Burkina Faso');
Insert into countries (id, name) values (371,'Burundi');
Insert into countries (id, name) values (372,'Cabo Verde');
Insert into countries (id, name) values (373,'Camerun');
Insert into countries (id, name) values (374,'Chad');
Insert into countries (id, name) values (375,'Comoras');
Insert into countries (id, name) values (376,'Costa de Marfil');
Insert into countries (id, name) values (377,'Egipto');
Insert into countries (id, name) values (378,'Eritrea');
Insert into countries (id, name) values (379,'Etiopia');
Insert into countries (id, name) values (380,'Gabon');
Insert into countries (id, name) values (381,'Gambia');
Insert into countries (id, name) values (382,'Ghana');
Insert into countries (id, name) values (383,'Guinea');
Insert into countries (id, name) values (384,'Guinea-Bisau');
Insert into countries (id, name) values (385,'Guinea Ecuatorial');
Insert into countries (id, name) values (386,'Kenia');
Insert into countries (id, name) values (387,'Lesoto');
Insert into countries (id, name) values (388,'Liberia');
Insert into countries (id, name) values (389,'Libia');
Insert into countries (id, name) values (390,'Madagascar');
Insert into countries (id, name) values (391,'Malaui');
Insert into countries (id, name) values (392,'Mali');
Insert into countries (id, name) values (393,'Marruecos');
Insert into countries (id, name) values (394,'Mauricio');
Insert into countries (id, name) values (395,'Mauritania');
Insert into countries (id, name) values (396,'Mozambique');
Insert into countries (id, name) values (397,'Namibia');
Insert into countries (id, name) values (398,'Niger');
Insert into countries (id, name) values (399,'Nigeria');
Insert into countries (id, name) values (400,'Republica Centroafricana');
Insert into countries (id, name) values (401,'Republica del Congo');
Insert into countries (id, name) values (402,'Republica Democratica del Congo');
Insert into countries (id, name) values (403,'Ruanda');
Insert into countries (id, name) values (404,'Santo Tome y Principe');
Insert into countries (id, name) values (405,'Senegal');
Insert into countries (id, name) values (406,'Seychelles');
Insert into countries (id, name) values (407,'Sierra Leona');
Insert into countries (id, name) values (408,'Somalia');
Insert into countries (id, name) values (409,'Suazilandia');
Insert into countries (id, name) values (410,'Sudafrica');
Insert into countries (id, name) values (411,'Sudan');
Insert into countries (id, name) values (412,'Sudan del Sur');
Insert into countries (id, name) values (413,'Tanzania');
Insert into countries (id, name) values (414,'Togo');
Insert into countries (id, name) values (415,'Tunez');
Insert into countries (id, name) values (416,'Uganda');
Insert into countries (id, name) values (417,'Yibuti');
Insert into countries (id, name) values (418,'Zambia');
Insert into countries (id, name) values (419,'Zimbabue');
Insert into countries (id, name) values (2246,'Antigua y Barbuda');
Insert into countries (id, name) values (231,'Bahamas');
Insert into countries (id, name) values (232,'Barbados');
Insert into countries (id, name) values (233,'Belice');
Insert into countries (id, name) values (235,'Brasil');
Insert into countries (id, name) values (236,'Canada');
Insert into countries (id, name) values (237,'Chile');
Insert into countries (id, name) values (238,'Colombia');
Insert into countries (id, name) values (239,'Costa Rica');
Insert into countries (id, name) values (240,'Cuba');
Insert into countries (id, name) values (241,'Dominica');
Insert into countries (id, name) values (242,'Ecuador');
Insert into countries (id, name) values (243,'El salvador');
Insert into countries (id, name) values (244,'Granada');
Insert into countries (id, name) values (245,'Guyana');
Insert into countries (id, name) values (246,'Haiti');
Insert into countries (id, name) values (247,'Guatemala');
Insert into countries (id, name) values (248,'Honduras');
Insert into countries (id, name) values (249,'Jamaica');
Insert into countries (id, name) values (250,'Mexico');
Insert into countries (id, name) values (251,'Nicaragua');
Insert into countries (id, name) values (252,'Panama');
Insert into countries (id, name) values (253,'Paraguay');
Insert into countries (id, name) values (254,'Peru');
Insert into countries (id, name) values (255,'Republica Dominicana');
Insert into countries (id, name) values (256,'San Cristobal y Nieves');
Insert into countries (id, name) values (257,'San Vicente');
Insert into countries (id, name) values (258,'Santa Lucia');
Insert into countries (id, name) values (259,'Surinam');
Insert into countries (id, name) values (260,'Trinidad y Tobago');
Insert into countries (id, name) values (261,'Venezuela');
Insert into countries (id, name) values (262,'Albania');
Insert into countries (id, name) values (263,'Alemania');
Insert into countries (id, name) values (264,'Andorra');
Insert into countries (id, name) values (265,'Austria');
Insert into countries (id, name) values (266,'Belgica');
Insert into countries (id, name) values (267,'Bielorrusia');
Insert into countries (id, name) values (268,'Bosnia y Herzegovina');
Insert into countries (id, name) values (269,'Bulgaria');
Insert into countries (id, name) values (270,'Chipre');
Insert into countries (id, name) values (271,'Croacia');
Insert into countries (id, name) values (272,'Dinamarca');
Insert into countries (id, name) values (273,'Eslovaquia');
Insert into countries (id, name) values (274,'Eslovenia');
Insert into countries (id, name) values (275,'Estonia');
Insert into countries (id, name) values (276,'Finlandia');
Insert into countries (id, name) values (277,'Grecia');
Insert into countries (id, name) values (278,'Hungria');
Insert into countries (id, name) values (279,'Irlanda');
Insert into countries (id, name) values (280,'Islandia');
Insert into countries (id, name) values (281,'Italia');
Insert into countries (id, name) values (282,'Letonia');
Insert into countries (id, name) values (283,'Liechtenstein');
Insert into countries (id, name) values (284,'Lituania');
Insert into countries (id, name) values (285,'Luxemburgo');
Insert into countries (id, name) values (286,'Macedonia');
Insert into countries (id, name) values (287,'Malta');
Insert into countries (id, name) values (288,'Moldavia');
Insert into countries (id, name) values (289,'Monaco');
Insert into countries (id, name) values (290,'Montenegro');
Insert into countries (id, name) values (291,'Noruega');
Insert into countries (id, name) values (292,'countrieses Bajos');
Insert into countries (id, name) values (293,'Polonia');
Insert into countries (id, name) values (294,'Portugal');
Insert into countries (id, name) values (295,'Reino Unido');
Insert into countries (id, name) values (296,'Republica Checa');
Insert into countries (id, name) values (297,'Rumania');
Insert into countries (id, name) values (298,'Rusia');
Insert into countries (id, name) values (299,'San Marino');
Insert into countries (id, name) values (300,'Serbia');
Insert into countries (id, name) values (301,'Suecia');
Insert into countries (id, name) values (302,'Suiza');
Insert into countries (id, name) values (303,'Ucrania');
Insert into countries (id, name) values (304,'Ciudad del Vaticano');
Insert into countries (id, name) values (305,'Afganistan');
Insert into countries (id, name) values (306,'Arabia Saudita');
Insert into countries (id, name) values (307,'Armenia');
Insert into countries (id, name) values (308,'Azerbaiyan');
Insert into countries (id, name) values (309,'Barein');
Insert into countries (id, name) values (310,'Banglades');
Insert into countries (id, name) values (311,'Birmania');
Insert into countries (id, name) values (312,'Butan');
Insert into countries (id, name) values (313,'Brunei');
Insert into countries (id, name) values (314,'Camboya');
Insert into countries (id, name) values (315,'China');
Insert into countries (id, name) values (316,'Corea del Norte');
Insert into countries (id, name) values (317,'Corea del Sur');
Insert into countries (id, name) values (318,'Emiratos Arabes Unidos');
Insert into countries (id, name) values (319,'Filipinas');
Insert into countries (id, name) values (320,'Georgia');
Insert into countries (id, name) values (321,'Indonesia');
Insert into countries (id, name) values (322,'India');
Insert into countries (id, name) values (323,'Iran');
Insert into countries (id, name) values (324,'Irak');
Insert into countries (id, name) values (325,'Israel');
Insert into countries (id, name) values (326,'Japon');
Insert into countries (id, name) values (327,'Jordania');
Insert into countries (id, name) values (328,'Kazajistan');
Insert into countries (id, name) values (329,'Kirguistan');
Insert into countries (id, name) values (330,'Kuwait');
Insert into countries (id, name) values (331,'Laos');
Insert into countries (id, name) values (332,'Libano');
Insert into countries (id, name) values (333,'Malasia');
Insert into countries (id, name) values (335,'Mongolia');
Insert into countries (id, name) values (336,'Nepal');
Insert into countries (id, name) values (337,'Oman');
Insert into countries (id, name) values (338,'Pakistan');
Insert into countries (id, name) values (339,'Catar');
Insert into countries (id, name) values (341,'Singapur');
Insert into countries (id, name) values (342,'Siria');
Insert into countries (id, name) values (343,'Sri Lanka');
Insert into countries (id, name) values (344,'Tailandia');
Insert into countries (id, name) values (345,'Tayikistan');
Insert into countries (id, name) values (346,'Timor Oriental');
Insert into countries (id, name) values (347,'Turkmenistan');
Insert into countries (id, name) values (348,'Turquia');
Insert into countries (id, name) values (349,'Uzbekistan');
Insert into countries (id, name) values (350,'Vietnam');
Insert into countries (id, name) values (351,'Yemen');
Insert into countries (id, name) values (352,'Australia');